CREATE GLOBAL TEMPORARY TABLE TASY.W_PROCESSO_ADEP
	(
	NR_SEQUENCIA           NUMBER (10) NOT NULL,
	DT_ATUALIZACAO         DATE NOT NULL,
	NM_USUARIO             VARCHAR2 (15) NOT NULL,
	DT_ATUALIZACAO_NREC    DATE,
	NM_USUARIO_NREC        VARCHAR2 (15),
	CD_PESSOA_FISICA       VARCHAR2 (10) NOT NULL,
	NR_ATENDIMENTO         NUMBER (10) NOT NULL,
	CD_SETOR_ATENDIMENTO   NUMBER (5),
	CD_UNIDADE_BASICA      VARCHAR2 (10),
	CD_UNIDADE_COMPL       VARCHAR2 (10),
	QT_TOTAL               NUMBER (15,4) NOT NULL,
	QT_DIETA_ATRAS         NUMBER (15,4) NOT NULL,
	QT_DIETA_FUTURO        NUMBER (15,4) NOT NULL,
	QT_SNE_ATRAS           NUMBER (15,4) NOT NULL,
	QT_SNE_FUTURO          NUMBER (15,4) NOT NULL,
	QT_SOLUCAO_ATRAS       NUMBER (15,4) NOT NULL,
	QT_SOLUCAO_FUTURO      NUMBER (15,4) NOT NULL,
	QT_MEDIC_ATRAS         NUMBER (15,4) NOT NULL,
	QT_MEDIC_FUTURO        NUMBER (15,4) NOT NULL,
	QT_PROCED_ATRAS        NUMBER (15,4) NOT NULL,
	QT_PROCED_FUTURO       NUMBER (15,4) NOT NULL,
	QT_GLICEMIA_ATRAS      NUMBER (15,4) NOT NULL,
	QT_GLICEMIA_FUTURO     NUMBER (15,4) NOT NULL,
	QT_RECOMENDACAO_ATRAS  NUMBER (15,4) NOT NULL,
	QT_RECOMENDACAO_FUTURO NUMBER (15,4) NOT NULL,
	QT_COLETA_ATRAS        NUMBER (15,4),
	QT_COLETA_FUTURO       NUMBER (15,4),
	QT_GASO_ATRAS          NUMBER (15,4),
	QT_GASO_FUTURO         NUMBER (15,4)
	)
	ON COMMIT PRESERVE ROWS
	NOCACHE;